-- AlterTable
ALTER TABLE "MarketToken" ADD COLUMN     "poolReserveToken" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "poolReserveUsdc" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "updatedAt" DROP DEFAULT;
